export const createAccountStyle = theme=>({
    container:{
        display:'flex',
        flexDirection:'column'
    },
    info:{
        fontWeight:'bold',
        marginTop:50,
        textAlign:'center',
        marginBottom:25
    },
    formContainer:{
        display:'flex',
        flexDirection:'row',
        justifyContent:'center',
        textAlign:'center',
        padding:20,
        marginLeft:80,
        width:'80%',
        [theme.breakpoints.down('xs')]:{
            marginLeft:0,
            width:'100%'
        }
    },
    form:{
        marginTop:70,
        display:'flex',
        flexDirection:'column',
        alignItems:'center',
        justifyContent:"center",
        width:'70%',
        [theme.breakpoints.down('xs')]:{
            width:'100%',
            display:'flex',
            flexDirection:'column',
            alignItems:'flex-start'
        }
    },
    inputContainer:{
        display:'flex',
        flexDirection:'row',
        marginBottom:50
    },
    text_input:{
        width:'80%',
        marginTop:20,
        marginBottom:15,
        [theme.breakpoints.down('xs')]:{
            width:'100%'
        }
    },
    gender:{
        display:"flex",
        flexDirection:'column',
        alignItems:'flex-start'
    },
    genderInnerLayout:{
        display:'flex',
        flexDirection:'row'
    },
    birthDate:{
        display:"flex",
        flexDirection:'column',
        alignItems:'flex-start',
        marginTop:-10,
    },
    grid:{
       marginBottom:80,
       [theme.breakpoints.down('xs')]:{
           marginBottom:10
       }
    },
    profile_pic:{
        display:'flex',
        flexDirection:'column',
        alignItems:'flex-start',
        marginLeft:55,
        marginTop:50,
        [theme.breakpoints.down('xs')]:{
            marginTop:10,
            marginBottom:20,
            marginLeft:10,
            width:'100%'
        }
    },
    create_btn:{
        [theme.breakpoints.down('xs')]:{
            width:'100%'
        }
    }
})

export default createAccountStyle